routes/backend.php
<?php
Route::get('{company}/user/logout', 'backend\UserController@logout');

Route::get('{company}', 'backend\Dashboard@index');

Route::any('{company}/page/edit/{slug?}', 'backend\Page@edit');

// User
Route::any('{company}/user/add/{role?}/{id?}', 'backend\User@add');
Route::any('{company}/user/{role?}', 'backend\User@index');
Route::any('{company}/change-password', 'backend\User@change_password');

// Account
Route::any('{company}/account/{role}', 'backend\AccountController@index');
Route::any('{company}/account/{role}/add/{id?}', 'backend\AccountController@add');

// Vehicle
Route::any('{company}/vehicle', 'backend\VehicleController@index');
Route::any('{company}/vehicle/add/{id?}', 'backend\VehicleController@add');

// Add-on Items
Route::any('{company}/unit', 'backend\UnitController@index');
Route::any('{company}/add-on-item', 'backend\ItemController@index');
Route::any('{company}/add-on-item/add/{id?}', 'backend\ItemController@add');

// Activity
Route::any('{company}/activity', 'backend\ActivityController@index');
Route::any('{company}/activity/add/{id?}', 'backend\ActivityController@add');

// Leads
Route::any('{company}/leads', 'backend\LeadController@index');
Route::any('{company}/leads/add/{id?}', 'backend\LeadController@add');
Route::any('{company}/leads/follow-up/{type}', 'backend\LeadController@follow_up');
Route::any('{company}/leads/management', 'backend\LeadController@management');

// Visa
Route::any('{company}/visa', 'backend\VisaController@index');
Route::any('{company}/visa/add/{id?}', 'backend\VisaController@add');
Route::any('{company}/visa/application/{id?}', 'backend\VisaController@application');
Route::any('{company}/visa/status/{id}/{status}', 'backend\VisaController@status');

// Location
Route::any('{company}/location/countries/{slug?}', 'backend\Location@country');
Route::post('{company}/location/country/import', 'backend\Location@import_country');
Route::get('{company}/location/country/export', 'backend\Location@export_country');

Route::any('{company}/location/states/{slug?}', 'backend\Location@states');
Route::post('{company}/location/state/import', 'backend\Location@import_state');
Route::get('{company}/location/state/export', 'backend\Location@export_state');

Route::any('{company}/location/cities/{slug?}', 'backend\Location@cities');
Route::post('{company}/location/city/import', 'backend\Location@import_city');
Route::get('{company}/location/city/export', 'backend\Location@export_city');

Route::any('{company}/location/pincode/{slug?}', 'backend\Location@pincode');
Route::post('{company}/location/pincode/import', 'backend\Location@import_pincode');
Route::get('{company}/location/pincode/export', 'backend\Location@export_pincode');

Route::any('{company}/department/{id?}', 'backend\DepartmentController@index');

Route::any('{company}/create-fixed-tour/{id?}', 'backend\TripController@add');
Route::any('{company}/hotels', 'backend\TripController@select_hotel');

// Profile
Route::any('{company}/edit-profile', 'backend\UserController@edit_profile');
Route::any('{company}/change-password', 'backend\UserController@change_password');

// Settings
Route::any('{company}/general-setting', 'backend\SettingController@index');

Route::any('{company}/ajax/user_login', 'backend\Ajax@user_login');
Route::any('{company}/ajax/{action}', 'backend\Ajax@index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});
Route::get('', 'Home@index');
Route::get('404-error', 'Home@index');

app/Http/Controllers/backend/ActivityController.php
<?php
namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\BaseController;

use App\Model\Activity;
use App\Model\User;
use App\Model\Role;

class ActivityController extends BaseController {
    public function index(Request $request, $company, $id = NULL) {
        $profile = $this->profile($request);

        $title 	= "Activity";
        $page 	= "view_activity";

        $search = $request->input('search');


        $query   =  Activity::where('activity_is_deleted', 'N')->where('activity_company', $profile->user_company);

        if(!empty($search['keyword'])) {
            $query->where(function($q) use($search) {
                $s = trim( $search['keyword'] );

                $q->where('activity_tilte', 'LIKE', '%'.$s.'%');
            });
        }

        $records = $query->orderBy('activity_id', 'DESC')->paginate(30);

        $data 	= compact('page', 'title', 'records', 'search');
        return view('backend/layout', $data);
    }

    public function add(Request $request, $company, $id = null) {
        $profile = $this->profile($request);

        if(!empty($id)) {
            $edit       = Activity::find($id);
        }

        $title 	= empty($edit->activity_id) ? "Add Activity" : "Edit Activity";
        $page 	= "add_activity";

        if($request->isMethod('post')) {
            $record = $request->input('record');

            $record['activity_updated_on']    = date('Y-m-d H:i:s', time());
            $record['activity_added_by']      = $profile->user_id;
            $record['activity_company']       = $profile->user_company;

            $record = array_filter($record);

            if(empty($id)) {
                $user['activity_created_on'] = date('Y-m-d H:i:s', time());
                $id = Activity::insertGetId($record);
            } else {
                Activity::where('activity_id', $id)->update($record);
            }
            if ($request->hasFile('activity_image')) {
                if(!empty($edit->activity_image) && file_exists(public_path()."/imgs/activities/".$edit->activity_image)) {
                    unlink(public_path()."/imgs/activities/".$edit->activity_image);
                }

                $image           = $request->file('activity_image');
                $name            = 'IMG'.$id.'.'.$image->getClientOriginalExtension();
                $destinationPath = "public/imgs/activities/";
                $image->move($destinationPath, $name);

                if(!empty($edit->user_image)) {
                    $name .= "?v=".uniqid();
                }

                Activity::where('activity_id', $id)->update( array('activity_image' => $name) );
            }

            return redirect("{$company}/activity/")->with('success', "Success! New Activity has been created.");
        }

        if(!empty($profile)) {
            $customers  = User::where('user_is_deleted', 'N')->where('user_role', 'customer')->where('user_company', @$profile->user_company)->get();
            $staffs     = User::where('user_is_deleted', 'N')->where('user_role', 'staff')->where('user_company', @$profile->user_company)->get();
        }


        $data 	    = compact('page', 'title', 'edit', 'customers', 'staffs');
        return view('backend/layout', $data);
    }
}

app/Http/Controllers/backend/Dashboard.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Routing\Controller as BaseController;
use Illuminate\Http\Request;
use DB;

class Dashboard extends BaseController {
   public function index() {
    	$title = "Dashboard";
    	$page  = "dashboard";
    	$data  = compact('page', 'title');
    	return view('backend/layout', $data);
    }
}

app/Http/Controllers/backend/Location.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\BaseController;
use App\Model\Country;
use App\Model\State;
use App\Model\City;
use App\Model\Pincode;

class Location extends BaseController {
    public function country(Request $request, $company, $id = null) {
        $profile = $this->profile($request);
    	$edit = [];
    	if(!empty($id)) {
    		$edit = Country::find($id);
    	}

    	if($request->isMethod('post')) {
    		$input = $request->input('record');
    		if(!empty($input)) {

                $isExistsQuery = Country::where(function($q) use ($input) {
                    $q->where('country_name', $input['country_name'])
                      ->orWhere('country_code', $input['country_code']);
                })->where('country_is_deleted', 'N');

                if(!empty($edit->country_id)) {
                    $isExistsQuery->where('country_id', '!=', $edit->country_id);
                }

                $isExists = $isExistsQuery->count();

                if(!$isExists) :
    	    		if(empty($edit->country_id)) {
    		    		$id   = Country::insertGetId($input);
                        $mess = "A new record has been added.";
    		    	} else {
    		    		Country::where('country_id', $id)->update($input);
                        $mess = "A record has been updated.";
    		    	}
                else :
                    return redirect($company.'/location/countries')->with('danger', 'Country name or code already exists.');
                endif;
		    }

		    $check = $request->input('check');
		    if(!empty($check)) {
		    	Country::whereIn('country_id', $check)->update(['country_is_deleted' => 'Y']);
                $mess = "A record has been removed.";
		    }

	    	return redirect($company.'/location/countries')->with('success', $mess);
    	}

        $query   = Country::withCount(['states', 'cities'])->where('country_is_deleted', 'N');
        $search  = $request->input('search');
        if(!empty($search['keyword'])) {
            $query->where(function($q) use($search) {
                $q->where('country_name', 'LIKE', '%'.$search['keyword'].'%')
                  ->orWhere('country_short_name', 'LIKE', '%'.$search['keyword'].'%')
                  ->orWhere('country_code', 'LIKE', '%'.$search['keyword'].'%');
            });
        }

    	$records = $query->orderBy('country_name', 'ASC')->paginate(30);

        $title 	= "Countries";
        $page 	= "country";
        $data 	= compact('page', 'title', 'records', 'edit', 'search');
        return view('backend/layout', $data);
    }
    public function export_country(Request $request, $company) {
        $records = Country::where('country_is_deleted', 'N')->get()->toArray();

        $fields = $values = [];
        foreach($records as $i => $rec) {
            if($i == 0) {
                $fields = array_keys($rec);
            }
            $values[] = array_values($rec);
        }

        $filename = "CountriesData_{$company}.csv";

        // disable caching
        $now = gmdate("D, d M Y H:i:s");
        header("Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate");
        header("Last-Modified: {$now} GMT");

        // force download
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");

        // disposition / encoding on response body
        header("Content-Disposition: attachment;filename={$filename}");
        header("Content-Transfer-Encoding: binary");

        ob_start();
        $df = fopen("php://output", 'w');
        fputcsv($df, $fields);
        foreach($values as $row) {
            fputcsv($df, $row);
        }
        fclose($df);
        return ob_get_clean();
    }
    public function import_country(Request $request, $company) {
        $file = $request->file('import_file');

        $fileName = $file->getPathName();

        $file = fopen($fileName, "r");
        $i = 0;
        while (($getData = fgetcsv($file, 10000, ",")) !== FALSE) {

            if($i == 0) {
                $fieldArr = $getData;
            } else {
                $row = array_combine( $fieldArr, $getData );

                Country::insert( $row );
            }

            $i++;
        }

        return redirect( url( $company.'/location/countries' ) )->with('success', 'Data has been imported.');
    }
    public function states(Request $request, $company, $id = null) {
        $edit = [];
        if(!empty($id)) {
            $edit = State::find($id);
        }

        if($request->isMethod('post')) {
            $input = $request->input('record');

            if(!empty($input)) {
                $isExistsQuery = State::where('state_name', $input['state_name'])->where('state_country', $input['state_country'])->where('state_is_deleted', 'N');

                if(!empty($edit->state_id)) {
                    $isExistsQuery->where('state_id', '!=', $edit->state_id);
                }

                $isExists = $isExistsQuery->count();

                if(!$isExists) :

                    if(empty($edit->state_id)) {
                        $id = State::insertGetId($input);
                        $mess = "A new record has been added.";
                    } else {
                        State::where('state_id', $id)->update($input);
                        $mess = "A record has been updated.";
                    }

                else :
                    return redirect()->back()->with('danger', 'State name in selected country is already exists.');
                endif;
            }

            $check = $request->input('check');
            if(!empty($check)) {
                State::whereIn('state_id', $check)->update(['state_is_deleted' => 'Y']);
                $mess = "A new record has been removed.";
            }

            return redirect($company.'/location/states')->with('success', $mess);
        }


        $countries  = Country::where('country_is_deleted', 'N')->get();
        $query      = State::with(['country'])->withCount(['cities'])->where('state_is_deleted', 'N');

        $search     = $request->input('search');
        if(!empty($search['country'])) {
            $query->where('state_country', $search['country']);
        }
        if(!empty($search['keyword'])) {
            $query->where(function($q) use($search) {
                $q->where('state_name', 'LIKE', '%'.$search['keyword'].'%')
                  ->orWhere('state_short_name', 'LIKE', '%'.$search['keyword'].'%');
            });
        }

        $records    = $query->paginate(10);

        $title  = "States";
        $page   = "state";
        $data   = compact('page', 'title', 'records', 'edit', 'countries', 'search');
        return view('backend/layout', $data);
    }
    public function export_state(Request $request, $company) {
        $records = State::join('countries AS c', 'states.state_country', 'c.country_id')->where('country_is_deleted', 'N')->select('states.*', 'c.country_name')->get()->toArray();

        $fields = $values = [];
        foreach($records as $i => $rec) {
            if($i == 0) {
                $fields = array_keys($rec);
            }
            $values[] = array_values($rec);
        }

        $filename = "StatesData_{$company}.csv";

        // disable caching
        $now = gmdate("D, d M Y H:i:s");
        header("Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate");
        header("Last-Modified: {$now} GMT");

        // force download
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");

        // disposition / encoding on response body
        header("Content-Disposition: attachment;filename={$filename}");
        header("Content-Transfer-Encoding: binary");

        ob_start();
        $df = fopen("php://output", 'w');
        fputcsv($df, $fields);
        foreach($values as $row) {
            fputcsv($df, $row);
        }
        fclose($df);
        return ob_get_clean();
    }
    public function import_state(Request $request, $company) {
        $file = $request->file('import_file');

        $fileName = $file->getPathName();

        $file = fopen($fileName, "r");
        $i = 0;
        while (($getData = fgetcsv($file, 10000, ",")) !== FALSE) {

            if($i == 0) {
                $fieldArr = $getData;
            } else {
                $row = array_combine( $fieldArr, $getData );
                $country = Country::where('country_name', $row['country_name'])
                            ->where('country_is_deleted', 'N')
                            ->select('country_id')
                            ->first();
                if(!empty($country->country_id)) {
                    $row['state_country'] = $country->country_id;
                } else {
                    $row['state_country'] = Country::insertGetId( ['country_name' => $row['country_name']] );
                }
                unset($row['country_name']);

                State::insert( $row );
            }

            $i++;
        }

        return redirect( url( $company.'/location/states' ) )->with('success', 'Data has been imported.');
    }

    public function cities(Request $request, $company, $id = null) {
        if($request->isMethod('post')) {
            $input = $request->input('record');
            if(!empty($input)) {
                if(empty($id)) {
                    $id = City::insertGetId($input);
                } else {
                    City::where('city_id', $id)->update($input);
                }
            }

            $check = $request->input('check');
            if(!empty($check)) {
                City::whereIn('city_id', $check)->update(['city_is_deleted' => 'Y']);
            }

resources/views/backend/inc/add_item.blade.php
<section class="page-header mb-3">
    <div class="container-fluid">
        <div class="clearfix">
            <div class="float-left">
                <h1><i class="icon-cart"></i> {{ !empty($edit->item_id) ? "Edit" : "Add" }} Item</h1>
                <ul class="page-breadcrumb">
                    <li><a href="{{ url($company) }}"><i class="icon-dashboard"></i> Dashboard</a></li>
                    <li><a href="{{ url($company.'/add-on-item') }}">Item</a></li>
                    <li class="active">{{ !empty($edit->item_id) ? "Edit" : "Add" }} Item</li>
                </ul>
            </div>
            <div class="float-right">
                <a href="{{ url($company.'/add-on-item/') }}" class="btn btn-primary">View Add-on Items</a>
            </div>
        </div>
    </div>
</section>
<div class="container-fluid">
    {{ Form::open(["files" => true]) }}
        @if (\Session::has('danger'))
            <div class="alert alert-danger">
                {!! \Session::get('danger') !!}</li>
            </div>
        @endif
    	<div class="row">
    		<div class="col-sm-8 col-lg-9">
                <div class="card">
                    <h3 class="card-title">Item Information</h3>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Item Name (Required)</label>
                                <input type="text" name="record[item_name]" value="{{ @$edit->item_name }}" placeholder="Name" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Unit (Required)</label>
                                <select class="form-control" name="record[item_unit]" required>
                                    <option value="">Select Unit</option>
                                    @foreach($units as $u)
                                    <option value="{{ $u->unit_id }}" @if(@$edit->item_unit == $u->unit_id) selected @endif>{{ $u->unit_name.' ('.$u->unit_short_name.')' }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Price (Required)</label>
                                <input type="number" name="record[item_price]" value="{{ @$edit->item_price }}" min="0" placeholder="Price" class="form-control" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="record[item_description]" rows="5" class="form-control" placeholder="Description"></textarea>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-lg-3">
                <div class="card">
                    <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </div>
                <div class="card">
                    <h3 class="card-title">Upload Image</h3>
                    <label class="upload_image">
                        <img src="{{ empty($edit->item_image) ? url('imgs/no-image.png') : url("imgs/items/".$edit->item_image) }}" alt="Upload Image" title="Upload Image">
                        <input type="file" name="item_image" accept="image/*" id="itemImage">
                    </label>
                    <label for="itemImage" class="btn btn-primary btn-block">Choose Image</label>
                </div>
            </div>
        {{ Form::close() }}
    </div>
</div>

resources/views/backend/inc/add_vehicle.blade.php
<section class="page-header mb-3">
    <div class="container-fluid">
        <div class="clearfix">
            <div class="float-left">
                <h1><i class="icon-tasks"></i> {{ !empty($edit->lead_id) ? "Edit" : "Add" }} Vehicle</h1>
                <ul class="page-breadcrumb">
                    <li><a href="{{ url($company) }}"><i class="icon-dashboard"></i> Dashboard</a></li>
                    <li><a href="{{ url($company.'/vehicles') }}">Vehicle</a></li>
                    <li class="active">{{ !empty($edit->vehicle_id) ? "Edit" : "Add" }} Vehicle</li>
                </ul>
            </div>
            <div class="float-right">
                <a href="{{ url($company.'/vehicle/') }}" class="btn btn-primary">View Vehicles</a>
            </div>
        </div>
    </div>
</section>
<div class="container-fluid">
    {{ Form::open(["files" => true]) }}
        @if (\Session::has('danger'))
            <div class="alert alert-danger">
                {!! \Session::get('danger') !!}</li>
            </div>
        @endif
    	<div class="row">
    		<div class="col-sm-8 col-lg-9">
                <div class="card">
                    <h3 class="card-title">Vehicle Information</h3>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Vehicle Make (Required)</label>
                                <input type="text" name="record[vehicle_make]" value="{{ @$edit->vehicle_make }}" placeholder="Vehicle Make" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Vehicle Model (Required)</label>
                                <input type="text" name="record[vehicle_model]" value="{{ @$edit->vehicle_model }}" placeholder="Vehicle Model" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Vehicle Seats with Driver (Required)</label>
                                <input type="tel" name="record[vehicle_seat]" value="{{ @$edit->vehicle_seat }}" placeholder="Vehicle Seat" class="form-control" required>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 col-lg-3">
                <div class="card">
                    <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </div>
            </div>
        {{ Form::close() }}
    </div>
</div>

resources/views/backend/inc/country.blade.php
<section class="page-header mb-3">
    <div class="container-fluid">
        <div class="clearfix">
            <div class="float-left">
                <h1><i class="icon-globe"></i> Country</h1>
                <ul class="page-breadcrumb">
                    <li><a href="{{ url($company_info->company_sitename) }}"><i class="icon-dashboard"></i> Dashboard</a></li>
                    <li class="active">Country</li>
                </ul>
            </div>
            <div class="float-right">
                {{ Form::open(['url' => url( $company_info->company_sitename.'/location/country/import'), 'files' => true]) }}
                <label class="btn btn-primary import_csv">
                    Import CSV
                    <input name="import_file" type="file" accept=".csv">
                </label>
                <a href="{{ url($company_info->company_sitename.'/location/country/export') }}" class="btn btn-primary">Export CSV</a>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</section>
<div class="container-fluid">
    @if (\Session::has('success'))
    <div class="alert alert-success">
        {!! \Session::get('success') !!}
    </div>
    @endif
    <div class="row">
        <div class="col-sm-4">
        	<div class="card">
                @if (\Session::has('danger'))
                <div class="alert alert-danger">
                    {!! \Session::get('danger') !!}
                </div>
                @endif
        	     <form method="post">
                     @csrf
              		 <h3 class="card-title"> <i class="icon-globe"></i> {{ !empty($edit->country_id) ? "Edit" : "Add" }} Country</h3>
                     <div class="form-group">
                         <label>Country Name (Required)</label>
                         <input type="text" name="record[country_name]" value="{{ @$edit->country_name }}" class="form-control" required>
                     </div>
                     <div class="form-group">
                         <label>Country Short Name (Required)</label>
                         <input type="text" name="record[country_short_name]" value="{{ @$edit->country_short_name }}" class="form-control" required>
                     </div>
                     <div class="form-group">
                         <label>Country Code (Required)</label>
                         <input type="text" name="record[country_code]" value="{{ @$edit->country_code }}" class="form-control" placeholder="Like +1,+91 etc." required>
                     </div>
                     <div class="form-group">
                         <button type="submit" class="btn btn-block btn-primary">Submit</button>
                     </div>
        		 </form>
        	</div>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <h3 class="card-title"><i class="icon-filter1"></i> Filter By</h3>
                {{ Form::open(['method' => 'GET']) }}
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <input type="text" name="search[keyword]" value="{{ @$search['keyword'] }}" class="form-control" placeholder="By keywords">
                        </div>
                    </div>
                    <div class="col-sm-3 col-xl-2">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"><i class="icon-search"></i> Search</button>
                        </div>
                    </div>
                </div>
                {{ Form::close() }}
            </div>
        	<div class="card">
                <form method="post">
                    @csrf
                    <a href="#remove" class="float-right" data-toggle="tooltip" title="Remove Selected"> <i class="icon-trash-o"></i> </a>
            		<h3 class="card-title">
                        <div class="mr-auto"><i class="icon-globe"></i> View Country</div>
            		</h3>
        		    @if(!$records->isEmpty())
        		    <div class="table-responsive">
        			    <table class="table table-bordered">
        			          <thead>
        			               <tr>
        			                    <th style="width: 50px;">
        			                        <label class="animated-checkbox">
        			                            <input type="checkbox" class="checkall">
        			                            <span class="label-text"></span>
        			                        </label>
        			                    </th>
        			                   <th style="width: 50px;">S.No.</th>
                                       <th>Country Name</th>
        			                   <th>Country Code</th>
        			                   <th>Country Short Name</th>
        			               </tr>
        			          </thead>

        			          <tbody>
        			          		@php $sn = $records->firstItem(); @endphp
        			          		@foreach($records as $rec)
        			               	<tr>
        		                        <td>
        		                            <label class="animated-checkbox">
        		                                <input type="checkbox" name="check[]" value="{{ $rec->country_id  }}" class="check @if($rec->states_count || $rec->cities_count) disabled @endif" @if($rec->states_count || $rec->cities_count) disabled @endif>
        		                                <span class="label-text"></span>
        		                            </label>
        		                        </td>
        								<td>{{ $sn++ }}</td>
                                        <td>
                                            <a href="{{ url($company_info->company_sitename.'/location/countries/'.$rec->country_id) }}" class="pencil">
                                                <i class="icon-pencil" title="Edit"></i> {{ $rec->country_name }}
                                            </a>
                                            ({{ $rec->states_count }} States | {{ $rec->cities_count }} Cities)
                                        </td>
        								<td>{{ $rec->country_code }}</td>
        								<td>{{ $rec->country_short_name }}</td>
        			               	</tr>
        			               @endforeach
        			          </tbody>
        			    </table>
        			</div>
                    @php
                        $get_param = request()->input();
                        if(isset($get_param['page'])) {
                            unset($get_param['page']);
                        }
                    @endphp
                    {{ $records->appends($get_param)->links() }}
        		    @else
        		    <div class="no_records_found">
        		      No records found yet.
        		    </div>
        			@endif
        		</form>
        	</div>
        </div>
    </div>

</div>